version: "3.7"

services:
  selenium:
    image: selenium/standalone-chrome:4.1.0-20211123
    ports:
      - 4444:4444
      - 7900:7900
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: streamlit run app.py --server.port 8000